apiVersion: apps/v1
kind: Deployment
metadata:
  name: radiologix-backend-deployment
  labels:
    app: radiologix-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: radiologix-backend
  template:
    metadata:
      labels:
        app: radiologix-backend
    spec:
      containers:
        - name: radiologix-backend
          image: bhaskar1612/radiologix-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: radiologix-backend-secret

---
apiVersion: v1
kind: Service
metadata:
  name: radiologix-backend-service
spec:
  selector:
    app: radiologix-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer