apiVersion: apps/v1
kind: Deployment
metadata:
  name: radiologix-frontend-deployment
  labels:
    app: radiologix-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: radiologix-frontend
  template:
    metadata:
      labels:
        app: radiologix-frontend
    spec:
      containers:
        - name: radiologix-frontend
          image: bhaskar1612/radiologix-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: radiologix-frontend-service
spec:
  selector:
    app: radiologix-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
